# Generated by Django 3.1.3 on 2021-01-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210112_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='task',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='test', max_length=150, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.TextField(default='test', verbose_name='text'),
            preserve_default=False,
        ),
    ]
