# Generated by Django 3.1.3 on 2021-01-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210113_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
    ]
