# Generated by Django 3.1.3 on 2021-01-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_partners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='text',
        ),
    ]
