# Generated by Django 3.1.3 on 2021-01-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210114_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='site_key_words',
            field=models.TextField(default='Site key words'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_logo',
            field=models.ImageField(default='Logo', upload_to=''),
            preserve_default=False,
        ),
    ]
