# Generated by Django 3.1.3 on 2021-01-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210114_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='address',
            field=models.CharField(default='Company address', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email',
            field=models.EmailField(default='Company email', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='insta',
            field=models.CharField(default='Company instagram', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='phone',
            field=models.TextField(default='Company phone', max_length=11),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_logo_text',
            field=models.CharField(default='text', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_logo',
            field=models.ImageField(upload_to='', verbose_name='Site Logo'),
        ),
    ]
