# Generated by Django 3.1.3 on 2021-01-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210114_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='phone',
            field=models.IntegerField(default='Company phone', max_length=11),
        ),
    ]
