# Generated by Django 3.1.3 on 2021-01-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210114_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='phone',
            field=models.IntegerField(default='Company phone', max_length=20),
        ),
    ]
