# Generated by Django 3.1.3 on 2021-01-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210114_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_text',
            field=models.TextField(default='About text'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_title',
            field=models.CharField(default='About title', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='map_html1',
            field=models.TextField(default='Map iframe1'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='map_html2',
            field=models.TextField(default='Map iframe2'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='phone2',
            field=models.BigIntegerField(default=89390000615, max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='phone',
            field=models.BigIntegerField(default='Company phone', max_length=20),
        ),
    ]
