# Generated by Django 3.1.3 on 2021-01-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210114_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='image', upload_to='', verbose_name='image'),
            preserve_default=False,
        ),
    ]
