# Generated by Django 3.1.3 on 2021-01-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210126_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blog/default.png', upload_to='blog', verbose_name='image'),
        ),
    ]
