# Generated by Django 3.1.3 on 2021-01-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
    ]
