# Generated by Django 3.1.3 on 2021-02-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210204_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Published')], default=0, max_length=1),
        ),
    ]
